"use client";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { products as staticProducts } from "@/data/products";
import type { Product } from "@/data/products";
import {
  Lock, Plus, Edit2, Trash2, CheckCircle2, XCircle, Copy, Check,
  FlaskConical, Eye, EyeOff, ArrowLeft, Save, Code2,
} from "lucide-react";

/* ─── Helpers ────────────────────────────────── */
const STORAGE_KEY = "peplab-admin-products";
const SESSION_KEY = "peplab-admin-auth";

function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function generateCode(products: Product[]): string {
  const json = JSON.stringify(products, null, 2);
  return `// AUTO-GENERATED by PepLab Admin — paste below the interface definitions
export const products: Product[] = ${json};\n`;
}

/* ─── Empty product template ─────────────────── */
const EMPTY: Partial<Product> = {
  id: "",
  slug: "",
  name: "",
  shortName: "",
  subtitle: "",
  description: "",
  longDescription: "",
  price: 0,
  originalPrice: undefined,
  concentration: "5mg",
  vialSize: "2mL",
  purity: "≥99%",
  sequence: "",
  molecularWeight: "",
  casNumber: "",
  storage: "Lyophilized: -20°C. Reconstituted: 2–8°C, use within 28 days.",
  category: "Research Peptides",
  tags: [],
  inStock: true,
  featured: true,
  stacksWith: [],
  benefits: ["", "", ""],
  researchAreas: [""],
  color: { primary: "#2563eb", secondary: "#1d4ed8", light: "#eff6ff", border: "#bfdbfe" },
  badge: "",
};

/* ─── Password gate ──────────────────────────── */
function PasswordGate({ onAuth }: { onAuth: () => void }) {
  const [pw, setPw]         = useState("");
  const [show, setShow]     = useState(false);
  const [error, setError]   = useState("");
  const [loading, setLoading] = useState(false);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/admin/auth", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ password: pw }),
      });
      if (res.ok) {
        sessionStorage.setItem(SESSION_KEY, "1");
        onAuth();
      } else {
        setError("Incorrect password.");
      }
    } catch {
      setError("Network error — try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#fafafa] flex items-center justify-center px-4">
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-2xl shadow-[0_8px_40px_rgba(0,0,0,0.08)] border border-neutral-100 p-10 w-full max-w-sm space-y-7"
      >
        <div className="text-center space-y-2">
          <div className="w-12 h-12 bg-[#2563eb] rounded-xl flex items-center justify-center mx-auto shadow-[0_4px_16px_rgba(37,99,235,0.3)]">
            <Lock className="w-5 h-5 text-white" />
          </div>
          <h1 className="text-xl font-bold text-[#09090b]" style={{ fontFamily: "var(--font-orbitron)" }}>
            PepLab Admin
          </h1>
          <p className="text-sm text-neutral-400">Enter your admin password to continue.</p>
        </div>

        <form onSubmit={submit} className="space-y-4">
          <div className="relative">
            <input
              type={show ? "text" : "password"}
              value={pw}
              onChange={(e) => setPw(e.target.value)}
              placeholder="Admin password"
              className="w-full px-4 py-3 rounded-xl border border-neutral-200 text-sm text-[#09090b] placeholder-neutral-400 focus:outline-none focus:ring-2 focus:ring-[#2563eb]/30 focus:border-[#2563eb] transition-all pr-11"
            />
            <button
              type="button"
              onClick={() => setShow(!show)}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-neutral-400 hover:text-neutral-600"
            >
              {show ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
            </button>
          </div>

          {error && (
            <p className="text-xs text-red-600 flex items-center gap-1.5">
              <XCircle className="w-3.5 h-3.5" /> {error}
            </p>
          )}

          <button
            type="submit"
            disabled={loading || !pw}
            className="w-full py-3 rounded-xl bg-[#09090b] text-white text-sm font-semibold hover:bg-[#1a1a1a] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? "Checking…" : "Enter Admin"}
          </button>
        </form>

        <p className="text-center text-[11px] text-neutral-300">
          Set <code className="font-mono bg-neutral-100 px-1 rounded">ADMIN_PASSWORD</code> in your Netlify env vars.
        </p>
      </motion.div>
    </div>
  );
}

/* ─── Product form modal ─────────────────────── */
function ProductForm({
  product,
  onSave,
  onClose,
}: {
  product: Partial<Product>;
  onSave: (p: Product) => void;
  onClose: () => void;
}) {
  const [form, setForm] = useState<Partial<Product>>({ ...EMPTY, ...product });

  const set = (key: string, val: unknown) =>
    setForm((f) => ({ ...f, [key]: val }));

  const handleName = (v: string) => {
    set("name", v);
    if (!product.id) {
      set("id", slugify(v));
      set("slug", slugify(v));
    }
  };

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    const p: Product = {
      id: form.id || slugify(form.name || "product"),
      slug: form.slug || slugify(form.name || "product"),
      name: form.name || "",
      shortName: form.shortName || form.name || "",
      subtitle: form.subtitle || "",
      description: form.description || "",
      longDescription: form.longDescription || form.description || "",
      price: Number(form.price) || 0,
      originalPrice: form.originalPrice ? Number(form.originalPrice) : undefined,
      concentration: form.concentration || "5mg",
      vialSize: form.vialSize || "2mL",
      purity: form.purity || "≥99%",
      sequence: form.sequence || "",
      molecularWeight: form.molecularWeight || "",
      casNumber: form.casNumber || "",
      storage: form.storage || "",
      category: form.category || "Research Peptides",
      tags: Array.isArray(form.tags) ? form.tags : [],
      inStock: form.inStock ?? true,
      featured: form.featured ?? true,
      stacksWith: Array.isArray(form.stacksWith) ? form.stacksWith : [],
      benefits: (form.benefits || []).filter(Boolean) as string[],
      researchAreas: (form.researchAreas || []).filter(Boolean) as string[],
      color: form.color || { primary: "#2563eb", secondary: "#1d4ed8", light: "#eff6ff", border: "#bfdbfe" },
      badge: form.badge || undefined,
    };
    onSave(p);
  };

  const field = (label: string, key: string, type = "text", placeholder = "") => (
    <div className="space-y-1">
      <label className="text-xs font-semibold text-neutral-500 uppercase tracking-wider">{label}</label>
      <input
        type={type}
        value={(form[key as keyof Product] as string) ?? ""}
        onChange={(e) => set(key, e.target.value)}
        placeholder={placeholder}
        step={type === "number" ? "0.01" : undefined}
        className="w-full px-3.5 py-2.5 rounded-xl border border-neutral-200 text-sm text-[#09090b] placeholder-neutral-300 focus:outline-none focus:ring-2 focus:ring-[#2563eb]/25 focus:border-[#2563eb] transition-all"
      />
    </div>
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center px-4 bg-black/40 backdrop-blur-sm">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-7 py-5 border-b border-neutral-100">
          <h2 className="font-bold text-[#09090b]" style={{ fontFamily: "var(--font-orbitron)" }}>
            {product.id ? "Edit Product" : "Add New Product"}
          </h2>
          <button onClick={onClose} className="p-2 rounded-lg hover:bg-neutral-100 transition-colors">
            <XCircle className="w-4 h-4 text-neutral-400" />
          </button>
        </div>

        {/* Form body */}
        <form onSubmit={submit} className="flex-1 overflow-y-auto px-7 py-6 space-y-5">
          <div className="grid grid-cols-2 gap-4">
            {field("Product Name *", "name", "text", "BPC-157")}
            {field("Short Name", "shortName", "text", "BPC-157")}
          </div>
          {field("Subtitle", "subtitle", "text", "Body Protection Compound")}
          <div>
            <label className="text-xs font-semibold text-neutral-500 uppercase tracking-wider">Short Description *</label>
            <textarea
              value={form.description || ""}
              onChange={(e) => set("description", e.target.value)}
              rows={3}
              className="mt-1 w-full px-3.5 py-2.5 rounded-xl border border-neutral-200 text-sm text-[#09090b] placeholder-neutral-300 focus:outline-none focus:ring-2 focus:ring-[#2563eb]/25 focus:border-[#2563eb] transition-all resize-none"
              placeholder="Brief product description..."
            />
          </div>
          <div className="grid grid-cols-3 gap-4">
            {field("Price ($) *", "price", "number", "54.99")}
            {field("Original Price ($)", "originalPrice", "number", "69.99")}
            {field("Concentration", "concentration", "text", "5mg")}
          </div>
          <div className="grid grid-cols-3 gap-4">
            {field("Purity", "purity", "text", "≥99%")}
            {field("Vial Size", "vialSize", "text", "2mL")}
            {field("Category", "category", "text", "Research Peptides")}
          </div>
          <div className="grid grid-cols-2 gap-4">
            {field("CAS Number", "casNumber", "text", "137525-51-0")}
            {field("Badge (optional)", "badge", "text", "BESTSELLER")}
          </div>

          {/* Color pickers */}
          <div className="space-y-2">
            <label className="text-xs font-semibold text-neutral-500 uppercase tracking-wider">Accent Color</label>
            <div className="flex gap-3 items-center">
              {[
                { label: "Primary", key: "primary", presets: ["#2563eb","#7c3aed","#d97706","#059669","#dc2626"] },
              ].map(({ label, key, presets }) => (
                <div key={key} className="flex-1 space-y-2">
                  <div className="text-[11px] text-neutral-400">{label}</div>
                  <div className="flex items-center gap-2">
                    <input
                      type="color"
                      value={form.color?.[key as keyof typeof form.color] || "#2563eb"}
                      onChange={(e) => set("color", { ...form.color, [key]: e.target.value })}
                      className="w-9 h-9 rounded-lg border border-neutral-200 cursor-pointer"
                    />
                    <div className="flex gap-1.5">
                      {presets.map((c) => (
                        <button
                          key={c}
                          type="button"
                          onClick={() => set("color", { ...form.color, [key]: c })}
                          className="w-6 h-6 rounded-md border border-neutral-200 hover:scale-110 transition-transform"
                          style={{ background: c }}
                        />
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Toggles */}
          <div className="flex gap-6">
            {[
              { label: "In Stock", key: "inStock" },
              { label: "Featured", key: "featured" },
            ].map(({ label, key }) => (
              <label key={key} className="flex items-center gap-2 cursor-pointer">
                <div
                  className={`w-9 h-5 rounded-full transition-colors relative ${
                    form[key as keyof Product] ? "bg-[#2563eb]" : "bg-neutral-200"
                  }`}
                  onClick={() => set(key, !form[key as keyof Product])}
                >
                  <div
                    className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform ${
                      form[key as keyof Product] ? "left-4" : "left-0.5"
                    }`}
                  />
                </div>
                <span className="text-sm font-medium text-neutral-600">{label}</span>
              </label>
            ))}
          </div>
        </form>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 px-7 py-5 border-t border-neutral-100">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl text-sm font-semibold text-neutral-600 border border-neutral-200 hover:bg-neutral-50 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={submit}
            className="px-5 py-2.5 rounded-xl text-sm font-semibold text-white bg-[#09090b] hover:bg-[#1a1a1a] transition-colors flex items-center gap-2"
          >
            <Save className="w-4 h-4" />
            Save Product
          </button>
        </div>
      </motion.div>
    </div>
  );
}

/* ─── Admin dashboard ────────────────────────── */
function AdminDashboard() {
  const [products, setProducts] = useState<Product[]>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      return stored ? JSON.parse(stored) : [...staticProducts];
    } catch {
      return [...staticProducts];
    }
  });

  const [editing, setEditing]   = useState<Partial<Product> | null>(null);
  const [adding,  setAdding]    = useState(false);
  const [showCode, setShowCode] = useState(false);
  const [copied,  setCopied]    = useState(false);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(products));
  }, [products]);

  const saveProduct = (p: Product) => {
    setProducts((prev) => {
      const idx = prev.findIndex((x) => x.id === p.id);
      if (idx >= 0) {
        const next = [...prev];
        next[idx] = p;
        return next;
      }
      return [...prev, p];
    });
    setEditing(null);
    setAdding(false);
  };

  const deleteProduct = (id: string) => {
    if (!confirm("Delete this product? This only affects the exported code.")) return;
    setProducts((prev) => prev.filter((p) => p.id !== id));
  };

  const toggleStock = (id: string) => {
    setProducts((prev) =>
      prev.map((p) => (p.id === id ? { ...p, inStock: !p.inStock } : p))
    );
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generateCode(products));
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const reset = () => {
    if (!confirm("Reset to static/shipped products?")) return;
    setProducts([...staticProducts]);
  };

  return (
    <div className="min-h-screen bg-[#fafafa]">
      {/* Top bar */}
      <header className="bg-white border-b border-neutral-100 px-6 py-4 flex items-center justify-between sticky top-0 z-30">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-xl bg-[#2563eb] flex items-center justify-center">
            <FlaskConical className="w-4 h-4 text-white" />
          </div>
          <div>
            <span className="font-bold text-[#09090b] text-sm" style={{ fontFamily: "var(--font-orbitron)" }}>
              PepLab <span className="text-[#2563eb]">Admin</span>
            </span>
            <p className="text-[11px] text-neutral-400">Product Management</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <a
            href="/admin/orders"
            className="flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold text-neutral-600 border border-neutral-200 hover:bg-neutral-50 transition-colors"
          >
            📦 Orders
          </a>
          <a
            href="/studio"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold text-[#7c3aed] border border-purple-200 hover:bg-purple-50 transition-colors"
          >
            🎨 Sanity CMS
          </a>
          <button
            onClick={reset}
            className="px-3.5 py-2 rounded-xl text-xs font-semibold text-neutral-500 border border-neutral-200 hover:bg-neutral-50 transition-colors"
          >
            Reset
          </button>
          <button
            onClick={() => setShowCode(!showCode)}
            className="flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold text-[#2563eb] border border-blue-200 hover:bg-blue-50 transition-colors"
          >
            <Code2 className="w-3.5 h-3.5" />
            Export Code
          </button>
          <button
            onClick={() => setAdding(true)}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold text-white bg-[#09090b] hover:bg-[#1a1a1a] transition-colors"
          >
            <Plus className="w-3.5 h-3.5" />
            Add Product
          </button>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8 space-y-6">

        {/* Export code panel */}
        <AnimatePresence>
          {showCode && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              className="bg-[#09090b] rounded-2xl overflow-hidden"
            >
              <div className="flex items-center justify-between px-6 py-4 border-b border-white/10">
                <div>
                  <p className="text-white font-semibold text-sm">Export products.ts</p>
                  <p className="text-neutral-400 text-xs mt-0.5">
                    Copy → paste into <code className="font-mono bg-white/10 px-1 rounded">src/data/products.ts</code> → git push → auto-deploys
                  </p>
                </div>
                <button
                  onClick={copyCode}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
                    copied
                      ? "bg-emerald-500 text-white"
                      : "bg-white/10 text-white hover:bg-white/20"
                  }`}
                >
                  {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? "Copied!" : "Copy Code"}
                </button>
              </div>
              <pre className="text-green-400 text-xs font-mono px-6 py-5 overflow-x-auto max-h-80 overflow-y-auto leading-relaxed whitespace-pre-wrap">
                {generateCode(products)}
              </pre>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Stats bar */}
        <div className="grid grid-cols-3 gap-4">
          {[
            { label: "Total Products", value: products.length },
            { label: "In Stock", value: products.filter((p) => p.inStock).length },
            { label: "Featured", value: products.filter((p) => p.featured).length },
          ].map((s) => (
            <div key={s.label} className="bg-white rounded-2xl border border-neutral-100 px-5 py-4">
              <div className="text-2xl font-black text-[#09090b]">{s.value}</div>
              <div className="text-xs text-neutral-400 font-medium mt-0.5">{s.label}</div>
            </div>
          ))}
        </div>

        {/* Product table */}
        <div className="bg-white rounded-2xl border border-neutral-100 overflow-hidden">
          <div className="px-6 py-4 border-b border-neutral-50">
            <h2 className="font-semibold text-[#09090b] text-sm">Products ({products.length})</h2>
          </div>

          <div className="divide-y divide-neutral-50">
            {products.map((product) => (
              <div key={product.id} className="px-6 py-4 flex items-center gap-4 hover:bg-neutral-50/50 transition-colors">
                {/* Color swatch */}
                <div
                  className="w-10 h-10 rounded-xl shrink-0 flex items-center justify-center font-bold text-xs text-white shadow-sm"
                  style={{ background: `linear-gradient(135deg, ${product.color.primary}, ${product.color.secondary})` }}
                >
                  {product.shortName?.slice(0, 2) || "??"}
                </div>

                {/* Name + info */}
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-sm text-[#09090b] truncate">{product.name}</div>
                  <div className="text-xs text-neutral-400 truncate">{product.subtitle}</div>
                </div>

                {/* Price */}
                <div className="text-sm font-bold text-[#09090b] shrink-0">${product.price.toFixed(2)}</div>

                {/* Stock toggle */}
                <button
                  onClick={() => toggleStock(product.id)}
                  className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold transition-colors shrink-0 ${
                    product.inStock
                      ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                      : "bg-neutral-100 text-neutral-500 border border-neutral-200"
                  }`}
                >
                  {product.inStock
                    ? <><CheckCircle2 className="w-3 h-3" /> In Stock</>
                    : <><XCircle className="w-3 h-3" /> Out of Stock</>}
                </button>

                {/* Actions */}
                <div className="flex items-center gap-1.5 shrink-0">
                  <button
                    onClick={() => setEditing(product)}
                    className="p-2 rounded-lg text-neutral-400 hover:text-[#2563eb] hover:bg-blue-50 transition-colors"
                    aria-label="Edit"
                  >
                    <Edit2 className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => deleteProduct(product.id)}
                    className="p-2 rounded-lg text-neutral-400 hover:text-red-600 hover:bg-red-50 transition-colors"
                    aria-label="Delete"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Instructions */}
        <div className="bg-amber-50 border border-amber-200 rounded-2xl px-6 py-5 space-y-2">
          <p className="text-sm font-semibold text-amber-800">How to publish changes</p>
          <ol className="text-xs text-amber-700 space-y-1 list-decimal list-inside">
            <li>Click <strong>Export Code</strong> above → click <strong>Copy Code</strong></li>
            <li>Open <code className="font-mono bg-amber-100 px-1 rounded">src/data/products.ts</code> in VS Code</li>
            <li>Replace the <code className="font-mono bg-amber-100 px-1 rounded">export const products</code> array with the copied code</li>
            <li>Save → <code className="font-mono bg-amber-100 px-1 rounded">git add . && git commit -m "update products" && git push</code></li>
            <li>Netlify auto-deploys in ~2 minutes 🚀</li>
          </ol>
        </div>
      </main>

      {/* Modals */}
      <AnimatePresence>
        {(editing || adding) && (
          <ProductForm
            product={editing || {}}
            onSave={saveProduct}
            onClose={() => { setEditing(null); setAdding(false); }}
          />
        )}
      </AnimatePresence>
    </div>
  );
}

/* ─── Page ───────────────────────────────────── */
export default function AdminPage() {
  const [authed, setAuthed] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined" && sessionStorage.getItem(SESSION_KEY)) {
      setAuthed(true);
    }
  }, []);

  if (!authed) {
    return <PasswordGate onAuth={() => setAuthed(true)} />;
  }

  return <AdminDashboard />;
}
